### PR TITLE
Fix for form upload update eating attachments

### PR DESCRIPTION
**Pull request by UnderpantsGnome**
@jnicklas This is a possible fix for the issue I mentioned [here](https://github.com/refile/refile/issues/6#issuecomment-101465403), the tests are passing.

### CODE REVIEW

**Comment by jnicklas** [comment]
This is not the right place to fix this problem. This should really be fixed inside `data`, possibly with a `select(&:present?)` or something. Also a failing test for this would be really nice.

**Comment by UnderpantsGnome** [comment]
@jnicklas I'll see if I can make some time to provide a better solution including test in the near future.

**Comment by jnicklas** [comment]
@UnderpantsGnome had some time to work on a fix for this. Can you give it a go and see if it solves your problem?

**Comment by UnderpantsGnome** [comment]
@jnicklas That change you made seems to have resolved the issue. Sorry about the delay, things have been a little busy.

**Pull request closed without merging**
