### PR TITLE
Don't care if no record. Possible when we have hm/ho :picture association

### PR DESCRIPTION
**Pull request by route**

### CODE REVIEW

**Comment by janko-m** [comment]
Sorry for not looking at this sooner. Could you provide an example where it happens that `nil` is passed in to the `#attachment_image_tag`?

**Comment by route** [comment]
I think it's common to have dedicated Picture model like: Product has many Pictures or has one Picture which could be not uploaded yet. For such products we'd like to show default picture or fallback in terms of `attachment_image_tag`. So basically the code looks:
```
= attachment_image_tag(product.picture, :image, :fit, 110, 110, fallback: 'default.jpg')
```

**Comment by janko-m** [comment]
Make sense! @jnicklas can we merge this?

**Comment by jnicklas** [comment]
I agree with this PR in principle, but the implementation is a bit strange. The code just doesn't read very clearly. Especially since we currently don't have any unit tests for this method, that makes me a bit apprehensive.

**Comment by janko-m** [comment]
I think if you just moved the `classes` line inside the `if file`, and then you can remove the conditional, it should really be fine without tests.

**Comment by jnicklas** [comment]
But we use `classes` even if there is no file.

**Comment by janko-m** [comment]
Lol, didn't see it properly. I think this is a really small change, so I think we could let it go without tests. @route, I just think in the second line you should write `if record` instead of `if file`, to keep the existing functionality (when record has no attachment, that it still gets the class by its name). Otherwise it reads clear to me.

**Comment by route** [comment]
@janko-m Agree, rebased/updated

**Comment by route** [comment]
Guys is it ok or should I refactor the whole method somehow?

**Comment by janko-m** [comment]
I was waiting for @jnicklas to approve, but maybe he's busy, and this is a really small change, so I'm merging it. Thanks :)

**Pull request merged**
