### PR TITLE
Remove metadata

### LINKED ISSUE #401: delete attachment
I have tried to add checkbox for the purpose to delete attached file.
I have  the following columns:
commented_id
commented_filename
commented_size
commented_content_type

actually only commented_id sets to NULL, other columns still maintain their values. Any suggestion?
thanks
Fabio

### PR DESCRIPTION
**Pull request by aglushkov**
This fixes #401, attachment metadata was not removed with attachment

### CODE REVIEW

**Comment by jnicklas** [comment]
The spec should probably be in `spec/refile/attachment_spec`, I think? There doesn't seem to be anything ActiveRecord specific in this from what I can tell.

**Comment by aglushkov** [comment]
Yes, a kind of redundant test. I will remove this from active_record_spec, and add one to attachment_spec

**Comment by aglushkov** [comment]
Ready

**Comment by jnicklas** [comment]
Awesome :) Thanks!

**Pull request merged**
