### PR TITLE
Nested attachments

### PR DESCRIPTION
**Pull request by aglushkov**
When updating attachments in nested models, it [fails](https://github.com/refile/refile/issues/142)
This is a fix

### CODE REVIEW

**Comment by janko-m** [comment]
This looks good. I didn't know ActiveRecord acted in that way, I thought it's always going to save the records, regardless of whether they're dirty or not. But I guess it works differently for nested models.

@jnicklas, merge?

**Comment by jnicklas** [comment]
I'm not a huge fan of how the tests are written. Defining constants in before blocks is very bad practice, imo, and bound to lead to tears later. I also really dislike inlining migrations like this. Migrations are slow, we should ideally not add and remove tables at runtime in the suite.

**Comment by janko-m** [comment]
Yeah, originally I thought to just merge (as accepting the idea), and then correct the tests, but we might forget and it's better that tests are right from the beginning.

@aglushkov You could reuse the existing "posts" table (see active_record_helper.rb), and add another table there. Then you can define the new nested model with `Class.new` as was done in the before block on the top of the test file.

**Comment by aglushkov** [comment]
I found that this solution only works for has_one association. I'll add more tests and rewrite this pull request

**Comment by janko-m** [comment]
Perfect, good job!

Before I also wanted to add this "will_change" behaviour, because e.g. the Sequel ORM only saves records when something changed (or you tell Sequel that it's going to change), so I thought that ActiveRecord might too, but ActiveRecod always saves the record. Except with has_one nested attributes.

**Comment by jnicklas** [comment]
Nice work @aglushkov. Tests look much better now :)

Weird question though: This assumes that `#{name}_id_will_change!` always is defined, can we make that assumption? It is currently possible, though as @janko-m noted: really weird, to define an attachment on a model without an ID column. Should we always assume there's an ID column. Should we always assume this column is a normal AR column?

**Comment by janko-m** [comment]
Well, if the ID column isn't a column (e.g. it's an attr_accessor), I don't think that use case would have made sense. Because users should always want to persist the image (especially on an AR model), otherwise it gets lost. Also I think in that case they were much better off using a PORO instead of an AR model.

One small downside of this functionality is that, if users forgot the create an ID column, they will get an `undefined method #{name}_id_will_change!` error instead of `undefined method #{name}`. But I think that users will rarely forget that, and they can still figure out from the first message what's going on.

**Comment by jnicklas** [comment]
Yeah, I think as you suggested somewhere else, we should just make it a hard error if there's no `id` column. Like it used to be.

**Pull request merged**
