### PR TITLE
simple_form integration

### PR DESCRIPTION
**Pull request by grosser**
@jnicklas 

now refile fields are no longer a 1-off I have to style by hand / think about / custom-css-ify :)

### CODE REVIEW

**Comment by ignisf** [comment]
Works well enough for me, however I needed to explicitly list `require: ['refile/rails', 'refile/simple_form']`.

I think this should be added to the `README.md` file together with the example use from the comments in the file.

**Comment by grosser** [comment]
added readme instructions

@jnicklas do you like this ?

**Comment by jnicklas** [comment]
Would it be possible to have the Refile options at the top level? As in:

``` ruby
<%= f.input :cover_image, as: :attachment, direct: true, presigned: true %>
```

That would be nicer, IMO.

**Comment by grosser** [comment]
done!

**Comment by grosser** [comment]
errors seem unrelated ... is master green ? ... can this get merged ?

**Comment by jnicklas** [comment]
Seems like a spurious failure. Restarted the Travis build and it looks good aside from a minor Rubucop niggle.

Do you think it makes sense to add a test for this functionality? It would require a lot of setup, so I'm not sure it'd be worth it, but might be nice to have. What do you think?

**Comment by grosser** [comment]
Testing this means adding simple_form, right ? Do you want that ?

**Comment by jnicklas** [comment]
@grosser as a development dependency yes. I think that's sensible.

**Comment by chrise86** [comment]
Has this been removed? I'm using:

    gem "refile", github: 'refile/refile', require: ['refile/rails', 'refile/simple_form']

but I'm getting:

    cannot load such file -- refile/simple_form

**Comment by grosser** [comment]
never got merged :(

**Comment by chrise86** [comment]
:(

**Comment by grosser** [comment]
updated and should be green, good to go ?

**Comment by grosser** [comment]
@jnicklas

**Comment by jnicklas** [comment]
Sorry for the delay. Looking really good. Merged!

**Comment by ignisf** [comment]
:tada:

**Comment by grosser** [comment]
Thx  :)

**Pull request merged**
