### PR TITLE
Better support for validating presence of attachment

### PR DESCRIPTION
**Pull request by monkbroc**
As discussed in #355, to validates the presence of an attachment, you should be able to do
```ruby
class Attachment < ActiveRecord::Base
  attachment :file
  validates_presence_of :file
end
```

Setting `attachment.file = nil` raises the exception `undefined method 'size' for nil:NilClass`. This PR fixes this by making `attachment.file = nil` mean the same thing as `attachment.remove_file = true`.

Setting `attachment.file = nil` or `attachment.remove_file = true` will still return the old file in `attachment.file` so the validation passes even though the file will be removed after save. This PR returns `nil` for `attachment.file` if `attacher.remove? == true`.

### CODE REVIEW

**Comment by jackturnbull** [comment]
Can't comment on the code within the PR as I haven't had chance to properly look at it but functionally this gets a +1 from me.

The current use of `validates_presence_of` directly on the attachment itself is incompatible with the shoulda-matcher [`validates_presence_of`](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb).

**Comment by monkbroc** [comment]
> The current use of validates_presence_of directly on the attachment itself is incompatible with the shoulda-matcher validates_presence_of.

This is what prompted me to make this PR.

**Comment by jackturnbull** [comment]
@monkbroc Is there any scenarios where user input would cause the uploaded file to be `nil`, rather than an empty string? As far as I can tell, if I have it as a required param, then this should always come from the controller as `''` rather than `nil` so I should be covered.

I think that there are inconsistencies that need to be resolved (hence the PR) but I'm debating how to guard against these in my app, or whether it's worth testing against these edge cases. How did you decide to approach this? Assuming you're not using your fork that is.

**Comment by monkbroc** [comment]
If the parameter is present in the request, it cannot be nil as you say. If it's not present, the `file=` method won't be called in `assign_attributes` so that's ok too.

I'm using my fork of course :laughing: 

Honestly this is more to make shoulda-matcher work well. It's not a situation that normally shows up so I feel this PR is low risk.

**Comment by jackturnbull** [comment]
> Honestly this is more to make shoulda-matcher work well. It's not a situation that normally shows up so I feel this PR is low risk.

Valuable to me also!

Cheers for the response, looks like I'll wrap it in a pending for now.

**Comment by jnicklas** [comment]
Looks good to me! Merging :) Sorry for the delay!

**Comment by monkbroc** [comment]
No worries. Thanks for taking time from your day to work on some open source :+1:

**Pull request merged**
