### PR TITLE
Resizing images before upload

### PR DESCRIPTION
**Pull request by cristhiano**
Gives support for max_width and max_height options for attachment_field helper so users can resize images before direct uploads

### CODE REVIEW

**Comment by 90caiosantos** [comment]
Very Helpful, thanks!

**Comment by chrishough** [comment]
+1 has this been merged?

**Comment by 90caiosantos** [comment]
not yet =/

**Comment by jnicklas** [comment]
This is an impressive PR, but it's also a bit scary. There's a *lot* of code I don't quite understand yet, and it seems very complicated for what it's trying to do. I really like the general idea though, client side rescaling before upload would be *very* cool.

I'm a bit wary. I think the code needs to be cleaned up. There need to be tests. We need to ensure this works on every browser, on every platform. There is *a lot* of work in getting this PR merged.

**Comment by cristhiano** [comment]
Hi @jnicklas, your right, it does need tests! I couldn't do it before but working on it now.

**Comment by chrishough** [comment]
If you need help with cross browser testing I am game @cristhiano.  I could boot up VMs for fun.  I am pretty sure from past JS projects using this type of functionality it only works in modern browsers IE > = 9

**Comment by cristhiano** [comment]
That will be great @chrishough! Your right, only modern browsers will do the job. I think that the big bottleneck is on Blob: http://caniuse.com/#search=Blob. IE 9 is out of picture because of this, but I don't think it's a problem since Refile it's already declared not compatible with IE 9. But maybe there is more problems, if you can clear this path will be awesome.

**Comment by chrishough** [comment]
How about we add a comment in the docs that states this feature is only supported in Modern? Also, I would have to dig this up but there is a js lib that can be used to test for browser version and shut this off for safety.

**Comment by cristhiano** [comment]
What about this: https://www.browserstack.com. It's free for open source projects.

**Comment by chrishough** [comment]
I have used that before, it is not bad.  I would think if we test in Chrome, Firefox, Safari, and IE >= 10 we should be ok.  MSFT is pulling all support for the older browsers anyway.  Just my 2 pennies. Thoughts?

**Comment by cristhiano** [comment]
I think that a Browserstack type of solution will cover us better when it comes to mobile devices. But in any case I will check for Blob constructing availability before rescaling images.

**Comment by chrishough** [comment]
Sounds good.  @jnicklas  do you think we need anything else on this?

**Comment by chrishough** [comment]
are we missing anything on this @jnicklas @cristhiano ?

**Comment by olliekav** [comment]
@jnicklas @cristhiano Is this close to being merged before I write my own hacky implementation? :)

**Comment by samuel012** [comment]
@cristhiano @chrishough any heads up as to when this will be merged?

**Comment by chrishough** [comment]
@samuel012 I would defer to @jnicklas @cristhiano

**Comment by sobrinho** [comment]
Hey, unfortunately, I'm going to close this one.

I don't think this belongs to Refile's core as you can use 3rd party javascript libraries for that and submit the resized file to the back-end deal with it later (just store in this case).

Since there are many options for that, I don't think one solution will be the answer for every user, I prefer to see Refile's core clean and small and delegate this to front-end teams.

**Pull request closed without merging**
