### PR TITLE
Added support for rack 2.0

### PR DESCRIPTION
**Pull request by sobrinho**
We had to upgrade webmock due to an issue with latest ruby.

### CODE REVIEW

**Comment by JoshTGreenwood** [comment]
Is there anything holding this PR back from merging? I'm happy to help in any way that I can as I'm currently blocked by this.

**Comment by sobrinho** [comment]
I'm going to fix the build and merge it.

**Comment by sobrinho** [comment]
Seems like I have to update rubocop, I'm going to do this later today 👍

**Comment by rddm2bb** [comment]
any update?

**Comment by sobrinho** [comment]
Busy days here :( You can use my fork until I work on rubocop and stuff.

**Comment by minimul** [comment]
👍

**Comment by sobrinho** [comment]
Not sure what's happening in jRuby.

Can anyone take a look? 🤔

**Comment by sobrinho** [comment]
Fixed, I will add support for rails 5.1 in another PR.

**Pull request merged**
